FROM python:3.11-slim

WORKDIR /app

COPY . /app/

ENV HOST=0.0.0.0
ENV PORT=4990
ENV CORE_CONFIG=""
ENV REQUIREMENTS_FILE=requirements.txt

ENV BLOOMZ_CONFIG=""
ENV CUSTOM_LIBRE_TRANSLATE_CONFIG=""
ENV DEEPL_CONFIG=""
ENV FB_MBART50_CONFIG=""
ENV FB_NLLB_CTRANSLATE2_CONFIG=""
ENV FB_NLLB_TRANSLATE_CONFIG=""
ENV GEMINI_CHAT_CONFIG=""
ENV GOOGLE_TRANSLATE_CONFIG=""
ENV KOBOLDAPI_TRANSLATE_CONFIG=""
ENV LIBRE_TRANSLATE_CONFIG=""
ENV LINGVANEX_CONFIG=""
ENV MULTI_SOURCES_CONFIG=""
ENV NO_TRANSLATE_CONFIG=""
ENV NO_TRANSLATE2_CONFIG=""
ENV OPENAI_CHAT_CONFIG=""
ENV OPUS_MT_CONFIG=""
ENV T5_MT_CONFIG=""
ENV USE_MID_LANG_CONFIG=""
ENV VSEGPT_CHAT_CONFIG=""


EXPOSE ${PORT}


CMD if [ -f "$REQUIREMENTS_FILE" ]; then \
      echo "Installation des dépendances depuis $REQUIREMENTS_FILE..."; \
      pip install --no-cache-dir -r "$REQUIREMENTS_FILE"; \
    else \
      echo "Aucun fichier $REQUIREMENTS_FILE trouvé. Skip install."; \
    fi && \
    python run_webapi.py